find_path(UTIL_INCLUDES
        *
        ${PROJECT_SOURCE_DIR}/utils/*)

find_library(UTIL_LIBRARIES NAMES UTIL PATH ${PROJECT_BINARY_DIR}/lib)

IF(UTIL_INCLUDES AND UTIL_LIBRARIES)
    SET(UTIL_FOUND TRUE)
    MESSAGE(STATUS "UTIL_FOUND true")
ENDIF(UTIL_INCLUDES AND UTIL_LIBRARIES)

IF(UTIL_FOUND)
    IF(NOT UTIL_FIND_REQUIRED)
        MESSAGE(STATUS "foundUTIL:" ${UTIL_INCLUDES})
        MESSAGE(STATUS "foundUTILtlib:" ${UTIL_LIBRARIES})
    ENDIF(NOT UTIL_FIND_REQUIRED)
ELSE(TEST_FOUND)
    IF(UTIL_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "could not find hello library")
    ENDIF(UTIL_FIND_REQUIRED)
ENDIF(UTIL_FOUND)